# Generated by Django 5.0.7 on 2024-07-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
